### ISSUE TITLE
Support for typescript in "colors-cli/toxic"

### ISSUE THREAD

**Issue by gustawdaniel** [jaywcjlove/colors-cli#8]
I typing

```
import 'colors-cli/toxic';

console.log("Preparing text file...".yellow);
```

I need support for autocompletion and do not want to see warnings in IDE

![2022-12-14_20-55](https://user-images.githubusercontent.com/16663028/207658516-96bf3dfe-12e1-4c17-be06-46c9d7f64091.png)

How to fix it?

**Comment by jaywcjlove** [comment]
@gustawdaniel Upgrade `v1.0.29`

**Comment by gustawdaniel** [comment]
@jaywcjlove it works! Thanks.
