### ISSUE TITLE
ES module for toxic

### ISSUE THREAD

**Issue by gustawdaniel** [jaywcjlove/colors-cli#9]
I have error

```
file:///home/daniel/pro/on-chain/custom-events/node_modules/colors-cli/toxic.js:1
const co = require('./lib/color');
           ^

ReferenceError: require is not defined in ES module scope, you can use import instead
    at file:///home/daniel/pro/on-chain/custom-events/node_modules/colors-cli/toxic.js:1:12
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

I am using `typescript`, `tsx` and importing by 

```
import 'colors-cli/toxic'
```

---

I am attaching fragment of tsx docs https://www.npmjs.com/package/tsx

> tsx is zero-config because it has smart detections built in. As a runtime, it detects what's imported to make many options in tsconfig.json redundant—which was designed for compiling matching files regardless of whether they're imported.

> It seamlessly adapts between CommonJS and ESM package types by detecting how modules are loaded (require() or import) to determine how to compile them. It even adds support for require()ing ESM modules from CommonJS so you don't have to worry about your dependencies as the ecosystem migrates to ESM.

---

I migrated my project from `tsx` to `rollup` with `@rollup/plugin-typescript`.

**Comment by gustawdaniel** [comment]
in watch mode rollup works but after build running it with `node` i see

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/daniel/pro/on-chain/custom-events/node_modules/colors-cli/toxic' imported from /home/daniel/pro/on-chain/custom-events/dist/app.js
Did you mean to import colors-cli/toxic.js?
```

**Comment by jaywcjlove** [comment]
@gustawdaniel Maybe solve your problem

Upgrade `1.0.30` to test?

**Comment by gustawdaniel** [comment]
It works! Thank you so much.
